-- Generated by Home Manager.
-- See https://wezfurlong.org/wezterm/

local wezterm = require 'wezterm'
local config = wezterm.config_builder()
config.color_scheme = "Catppuccin Mocha"
config.font_size = 13.0
config.font = wezterm.font "EnvyCodeR Nerd Font Mono"
-- config.window_decorations = 'RESIZE'
config.audible_bell = "Disabled"
config.hide_tab_bar_if_only_one_tab = true
return config

